### ISSUE TITLE
Need to define static ip related variable for non-static-ip case

### ISSUE THREAD

**Issue by s1061123** [redhat-nfvpe/ansible-role-vm-spinup#20]
Running kube-ansible with latest ansible-role-vm-spinup, it failed with following messages:

```
TASK [redhat-nfvpe.vm-spinup : Template the SSH spinup script] *****************************************************************************************************************************************************************************************************************
fatal: [vmhost]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'system_network' is undefined"}
```

The variable "system_network" seems to be used only for static ip assign case, however, ansible is trying to filling these variables into spinup.sh for all case hence "AnsibleUndefinedVariable" is occured.

**Comment by leifmadsen** [comment]
@s1061123 can you try out my PR and see if that resolves this problem? If so, please merge it down!
